general:
  name: "ambient-agent"
  description: "This is an ambient agent that can be integrated within slack to provide routine updates on AWS monitoring and resource utilization across accounts"

# This contains the model information for various agents
# in our multi agentic system
model_information:
  # Represents the model id that the agent will use within the system
  # as an deep agent model
  model_id: us.anthropic.claude-3-7-sonnet-20250219-v1:0
  system_prompt_fpath: prompt_templates/ambient_agent_system_prompt.txt
  # Represents the inference parameters that the foundation model
  # uses at runtime during inference
  inference_parameters:
    temperature: 0.1
    max_tokens: 4096  
    top_p: 0.92
    caching: true